def type(@dho_subnet_mask), do: :ip
def type(@dho_time_offset), do: :integer
def type(@dho_routers), do: :iplist
def type(@dho_time_servers), do: :iplist
def type(@dho_name_servers), do: :iplist
def type(@dho_domain_name_servers), do: :iplist
def type(@dho_log_servers), do: :iplist
def type(@dho_cookie_servers), do: :iplist
def type(@dho_lpr_servers), do: :iplist
def type(@dho_impress_servers), do: :iplist
def type(@dho_resource_location_servers), do: :iplist
def type(@dho_host_name), do: :string
def type(@dho_boot_size), do: :short
def type(@dho_merit_dump), do: :string
def type(@dho_domain_name), do: :string
def type(@dho_swap_server), do: :ip
def type(@dho_root_path), do: :string
def type(@dho_extensions_path), do: :string
def type(@dho_ip_forwarding), do: :byte
def type(@dho_non_local_source_routing), do: :byte
def type(@dho_policy_filter), do: :iplist
def type(@dho_max_dgram_reassembly), do: :short
def type(@dho_default_ip_ttl), do: :byte
def type(@dho_path_mtu_aging_timeout), do: :integer
def type(@dho_path_mtu_plateau_table), do: :integer
def type(@dho_interface_mtu), do: :short
def type(@dho_all_subnets_local), do: :byte
def type(@dho_broadcast_address), do: :ip
def type(@dho_perform_mask_discovery), do: :byte
def type(@dho_mask_supplier), do: :byte
def type(@dho_router_discovery), do: :byte
def type(@dho_router_solicitation_address), do: :ip
def type(@dho_static_routes), do: :iplist
def type(@dho_trailer_encapsulation), do: :byte
def type(@dho_arp_cache_timeout), do: :integer
def type(@dho_ieee802_3_encapsulation), do: :byte
def type(@dho_default_tcp_ttl), do: :byte
def type(@dho_tcp_keepalive_interval), do: :integer
def type(@dho_tcp_keepalive_garbage), do: :byte
def type(@dho_nis_domain), do: :string
def type(@dho_nis_servers), do: :iplist
def type(@dho_ntp_servers), do: :iplist
def type(@dho_tftp_server_name), do: :string
def type(@dho_bootfile_name), do: :string
def type(@dho_vendor_encapsulated_options), do: :vendor
def type(@dho_netbios_name_servers), do: :iplist
def type(@dho_netbios_dd_servers), do: :iplist
def type(@dho_netbios_node_type), do: :byte
def type(@dho_netbios_scope), do: :string
def type(@dho_font_servers), do: :iplist
def type(@dho_x_display_managers), do: :iplist
def type(@dho_dhcp_requested_address), do: :ip
def type(@dho_dhcp_lease_time), do: :integer
def type(@dho_dhcp_option_overload), do: :byte
def type(@dho_dhcp_message_type), do: :byte
def type(@dho_dhcp_server_identifier), do: :ip
def type(@dho_dhcp_parameter_request_list), do: :string
def type(@dho_dhcp_message), do: :string
def type(@dho_dhcp_max_message_size), do: :short
def type(@dho_dhcp_renewal_time), do: :integer
def type(@dho_dhcp_rebinding_time), do: :integer
def type(@dho_vendor_class_identifier), do: :string
def type(@dho_dhcp_client_identifier), do: :string
def type(@dho_nwip_domain_name), do: :string
def type(@dho_nis_plus_domain), do: :string
def type(@dho_nis_plus_servers), do: :iplist
def type(@dho_mobile_ip_home_agents), do: :iplist
def type(@dho_smtp_servers), do: :iplist
def type(@dho_pop3_servers), do: :iplist
def type(@dho_www_servers), do: :iplist
def type(@dho_finger_servers), do: :iplist
def type(@dho_irc_servers), do: :iplist
def type(@dho_streettalk_servers), do: :iplist
def type(@dho_stda_servers), do: :iplist
def type(@dho_user_class), do: :string
def type(@dho_fqdn), do: :string
def type(@dho_dhcp_agent_options), do: :string
def type(@dho_nds_servers), do: :iplist
def type(@dho_nds_tree_name), do: :string
def type(@dho_nds_context), do: :string
def type(@dho_uap), do: :string
def type(@dho_auto_configure), do: :byte
def type(@dho_name_service_search), do: :shortlist
def type(@dho_subnet_selection), do: :ip
def type(@dho_tftp_server_address), do: :ip
